---
engines:
  fixme:
    enabled: true
  gofmt:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "**.md"
  - "**.yml"
  - "**.json"
